### ISSUE TITLE
hangs in "starting"

### ISSUE THREAD

**Issue by G-Mein** [bitfocus/companion-module-twitch-api#11]
**Describe the bug**
I extracted the source to the bundled-modules folder and started companion again.

**To Reproduce**
As I added the twitch module in the right side, it tries to start but nothing happens.

I can't find anything to config or smthing. Any further informations yet? Did I do something wrong? sorry

**Comment by thedist** [comment]
Why are you extracting the source anywhere? The bundled modules folder is not intended to be touched, as that's the modules the Companion core team have set up. If you're attempting to code and submit changes to this module you should be testing in the module-local-dev folder.

Additionally, both the latest stable version of Companion, and Companion v3 which is in beta have a bundled version of the Twitch API module already.
