### ISSUE TITLE
"Open channel in default browser" not redirecting to specified channel

### ISSUE THREAD

**Issue by ianmdesign** [bitfocus/companion-module-twitch-api#2]
I've entered my channel name into the twitch companion module under the "Channels to monitor - space separated" entry field, but the "Open Channel in Default Browser" will redirect to [twitch.tv/null](https://twitch.tv/null) instead.

**Comment by thedist** [comment]
Apologies for the late reply. Are you able to share your channel list, I'm not able to replicate your issue.

**Comment by ianmdesign** [comment]
I dont believe i was able to, but im not using this module anymore. Feel free to close this issue if you want
