### ISSUE TITLE
Not possible to select other channels

### ISSUE THREAD

**Issue by sitzmoebelchronograph** [bitfocus/companion-module-twitch-api#3]
Hey guys,

I want to switch from streamdeck software to companion, but the twitch plugin has a "bug".

As a moderator of a lot of channels you have a lots of shortcut's on the deck for each channel. 
Something like this:
"Send messsage !schedule to channel". On all other streamdeck solution I can select the channal I want to send a message.
But on companion with the twitch extention I only can send message to my own channel.
This is ok for a single small streamer but for moderators it is not enough.

Please change the channel drop down into a freetext field I can enter a channel by myself to fix this issue :)

Thx a lot!

**Comment by thedist** [comment]
Thanks for the idea, this is something that's in the works for the next version, not just for selecting a channel to send messages to but also for controlling polls, predictions, extensions, and more. I don't currently have a timeline for when this will be ready but I hope to have it released in the comings weeks.
